version: 2.1
orbs:
  matlab: mathworks/matlab@1
  win: circleci/windows@5

# Define the execution environments for different operating systems
executors:
  linux:
    machine:
      image: default
  macos:
    macos:
      xcode: 16.4.0
  windows:
    win/default

jobs:
  split-test:
    parameters:
      os:
        type: executor
    executor: << parameters.os >>
    # Use parallelism to split tests across multiple containers
    parallelism: 2
    steps:
      - checkout
      
      # Install MATLAB and required products
      - matlab/install:
          products: >
            MATLAB_Compiler_SDK
            MATLAB_Test
      
      # Builds mex file and Python package from MATLAB function
      - matlab/run-build:
          tasks: mex buildPythonPackage
      
      # Run MATLAB tests, splitting them across parallel containers
      - matlab/run-tests:
          select-by-name: $(circleci tests glob "tests/**/*.m" | circleci tests split | awk -F'[\\\\/.]' '{print $(NF-1) "/*"}')

workflows:
  test-splitting-build:
    jobs:
      # A job will run for each OS present in the matrix
      - split-test:
          matrix:
            parameters:
              os: [linux, macos, windows]